### ISSUE TITLE
[PE-D][Tester A] module_search no example

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#94] opened 2024-04-05 19:37 UTC
![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/c64654c9-739f-4fc5-9e9f-f648ac884780.png)
The module_search has no example.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: DominicFuMJ/ped#7

**Comment by yadunut** [comment] 2024-04-07 08:49
Duplicate of #99.

**Closed as not planned by yadunut** 2024-04-07 08:49 UTC
