### ISSUE TITLE
[PE-D][Tester C] User Guide's Command Summary is Incomplete

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-2/tp#102] opened 2024-04-05 20:36 UTC
The command summary section of the user guide is expected to provide a comprehensive list of all available commands and features within the application. However, it currently does not list all available commands and features introduced. This creates a discrepancy between the documentation and the actual functionality.

Commands not included: add_module, delete_module, add_timing, delete_timing, find_free_time, list_modules, module_search

![image.png](https://raw.githubusercontent.com/ejnan/ped/main/files/c36ba4ee-9bcd-4acc-b2b3-ad8c9598f7bb.png)

![image.png](https://raw.githubusercontent.com/ejnan/ped/main/files/b9b87c45-a2b3-42ed-9104-a1ac0efae94a.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: ejnan/ped#8

**Comment by AdityaB4** [comment] 2024-04-09 14:30
Duplicate of #111. Accepted but closing.

**Closed as completed by AdityaB4** 2024-04-09 14:30 UTC
Labels: documentation
